version: '2.4'

services:
  app:
    image: {{cookiecutter.app_name}}
    container_name: {{cookiecutter.app_name}}
    build: .
    # Allow container to be attached to, e.g., to access the pdb shell
    stdin_open: true
    tty: true
    ports:
      # Map ports on your computer to ports on your container. This allows you,
      # e.g., to visit your containerized application in a browser on your
      # computer.
      - 8000:8000
    depends_on:
      postgres:
        condition: service_healthy
    volumes:
      # Mount the development directory as a volume into the container, so
      # Docker automatically recognizes your changes.
      - .:/app{% if cookiecutter.local_settings != 'None' %}
      - ${PWD}/{{cookiecutter.local_settings}}:/app/{{cookiecutter.local_settings|replace(".example", "")}}{% endif %}
    command: {{cookiecutter.run_command}}{% if cookiecutter.auto_migrate == 'True' %}

  migration:
    container_name: {{cookiecutter.app_name}}-migration
    image: {{cookiecutter.app_name}}:latest
    depends_on:
      # Declaring this dependency ensures that your application image is built
      # before migrations are run, and that your application and migrations can
      # be run from the same image, rather than creating purpose-specific
      # copies.
      - app
    volumes:
      # These should generally be the same as your application volumes.
      - .:/app{% if cookiecutter.local_settings != 'None' %}
      - ${PWD}/{{cookiecutter.local_settings}}:/app/{{cookiecutter.local_settings|replace(".example", "")}}{% endif %}
    command: {{cookiecutter.migrate_command}}
{% endif %}
  postgres:
    container_name: {{cookiecutter.app_name}}-postgres
    image: {% if cookiecutter.postgis == 'True' %}mdillon/postgis{% else %}postgres{% endif %}:{{cookiecutter.pg_version}}
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5
    environment:
      # The default Postgres image exposes a number of environmental variables
      # that allow you to configure the container's behavior, without writing
      # any additional code. Specify the name of your database, and any other
      # variables, here. https://hub.docker.com/_/postgres/#environment-variables
      - POSTGRES_DB={{cookiecutter.pg_db}}
      - POSTGRES_PASSWORD=postgres
    volumes:
      # By default, Postgres instantiates an anonymous volume. Use a named
      # one, so your data persists beyond the life of the container. See this
      # post for a discussion of the pitfalls of Postgres and anonymous
      # volumes: https://linuxhint.com/run_postgresql_docker_compose/
      - {{cookiecutter.app_name}}-db-data:/var/lib/postgresql/data
    ports:
      - 32001:5432

volumes:
  # Declare your named volume for Postgres.
  {{cookiecutter.app_name}}-db-data:
