repos:
  # Standard pre-commit hooks
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v2.3.0
    hooks:
      - id: check-yaml
      - id: end-of-file-fixer
      - id: trailing-whitespace

  # Black config (Python formatter)
  - repo: https://github.com/psf/black
    rev: 22.3.0
    hooks:
      - id: black
        exclude: ^({{ cookiecutter.module_name }}/migrations/)

  # Flake8 config (Python linter)
  # See ./.flake8 for additional configs
  - repo: https://github.com/pycqa/flake8
    rev: "9f60881"
    hooks:
      - id: flake8
        args: [--config=.flake8]

  # DjHTML config (Django template indenter)
  - repo: https://github.com/rtts/djhtml
    rev: v1.5.1
    hooks:
      - id: djhtml
        # Indent only HTML files in template directories
        files: .*/templates/.*\.html$
        args: [--tabwidth=2]

  # Prettier config (Javascript formatter)
  # See ./.prettierjson.rc for additional configs
  - repo: https://github.com/pre-commit/mirrors-prettier
    rev: v2.5.1
    hooks:
      - id: prettier
        exclude: ^(workplace/static/js/lib/|workplace/static/css/bootstrap|workplace/templates/)
        files: \.(js|ts|jsx|tsx|css|less|json|markdown|md|yaml|yml)$

  # Eslint config (Javascript linter)
  # See ./.eslintrc.js for additional configs
  - repo: https://github.com/pre-commit/mirrors-eslint
    rev: "1f7d592"
    hooks:
      - id: eslint
        additional_dependencies:
          - eslint@8.19.0
          - eslint-plugin-react@7.30.1
          - eslint-config-prettier@8.5.0
