FROM node:18 AS webpack

# Give ourselves some credit
LABEL maintainer "DataMade <info@datamade.us>"

# Inside the container, create an app directory and switch into it
RUN mkdir /app
WORKDIR /app

# Install Node requirements
COPY ./package.json /app/package.json
RUN npm install

FROM python:3.10 AS app

LABEL maintainer "DataMade <info@datamade.us>"

RUN curl -sL https://deb.nodesource.com/setup_18.x | bash -

RUN apt-get install -y --no-install-recommends postgresql-client nodejs{% if cookiecutter.postgis == 'True' %} gdal-bin{% endif %}

RUN mkdir /app
WORKDIR /app

COPY ./requirements.txt /app/requirements.txt
RUN pip install --no-cache-dir -r requirements.txt

COPY --from=webpack /app/node_modules /app/node_modules

COPY . /app

# Add a bogus env var for the Django secret key in order to allow us to run
# the 'collectstatic' management command
ENV DJANGO_SECRET_KEY 'foobar'
RUN python manage.py collectstatic --noinput
