name: CI

on:
  push:
    branches:
      - main
      - deploy
  pull_request:
    branches:
      - main

jobs:
  test:
    name: Run tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Build containers and run tests
        run: docker-compose -f docker-compose.yml -f tests/docker-compose.yml run --rm app
